/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mathes;

import java.sql.JDBCType;

/**
 *
 * @author Win-7
 */
public class mathes extends javax.swing.JFrame {
Comman comman = new Comman();
    /**
     * Creates new form mathes
     */
    public mathes() {
        initComponents();
        buttonGroup.add(jRadioButtonHours);
        buttonGroup.add(jRadioButtonMinute);
        jPanelwelcome.setVisible(true);
        Time_check.setVisible(false);
        jPanelAlzabric.setVisible(false);
        jPanelVelocity.setVisible(false);
        jTextFieldAPowerValue.setVisible(false);
        jTextFieldBpowervalue.setVisible(false);
        jTextFieldAvalue.setVisible(false);
        jTextFieldBvalue.setVisible(false);
        jTextFieldResultValue.setVisible(false);
        jComboBoxOpration.setVisible(false);
        jLabelequal.setVisible(false);
        jButtonOperation.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        Time_check = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldSpeed = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldTime = new javax.swing.JTextField();
        JTextFieldDistance = new javax.swing.JTextField();
        jButtontime = new javax.swing.JButton();
        JlableTime = new javax.swing.JLabel();
        jLabelSpeed = new javax.swing.JLabel();
        jLabelDistance = new javax.swing.JLabel();
        jButtonSpeed = new javax.swing.JButton();
        jButtonDistance = new javax.swing.JButton();
        jRadioButtonMinute = new javax.swing.JRadioButton();
        jRadioButtonHours = new javax.swing.JRadioButton();
        jRadioButtonSpeedKiloMeter = new javax.swing.JRadioButton();
        jRadioButtonDistenceKiloMeter = new javax.swing.JRadioButton();
        jPanelwelcome = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelAlzabric = new javax.swing.JPanel();
        jComboBoxSetoption = new javax.swing.JComboBox<>();
        jTextFieldAvalue = new javax.swing.JTextField();
        jTextFieldAPowerValue = new javax.swing.JTextField();
        jTextFieldBvalue = new javax.swing.JTextField();
        jTextFieldBpowervalue = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButtonOperation = new javax.swing.JButton();
        jLabelequal = new javax.swing.JLabel();
        jTextFieldResultValue = new javax.swing.JTextField();
        jComboBoxOpration = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanelVelocity = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldvelocity = new javax.swing.JTextField();
        jTextFinalPosition = new javax.swing.JTextField();
        jTextFieldInitialPosition = new javax.swing.JTextField();
        jTextFieldtimevelocity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Speed");

        jLabel2.setText("Time");

        jLabel3.setText("Distance");

        jButtontime.setText("Time");
        jButtontime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtontimeActionPerformed(evt);
            }
        });

        JlableTime.setText("Time");
        JlableTime.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JlableTimeMouseClicked(evt);
            }
        });

        jLabelSpeed.setText("Speed");
        jLabelSpeed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelSpeedMouseClicked(evt);
            }
        });

        jLabelDistance.setText("Distance");
        jLabelDistance.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelDistanceMouseClicked(evt);
            }
        });

        jButtonSpeed.setText("Speed");
        jButtonSpeed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpeedActionPerformed(evt);
            }
        });

        jButtonDistance.setText("Distance");
        jButtonDistance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDistanceActionPerformed(evt);
            }
        });

        jRadioButtonMinute.setText("Minute");

        jRadioButtonHours.setText("Hours");

        jRadioButtonSpeedKiloMeter.setText("Kilo Meter");
        jRadioButtonSpeedKiloMeter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSpeedKiloMeterActionPerformed(evt);
            }
        });

        jRadioButtonDistenceKiloMeter.setText("Kilo Meter");

        javax.swing.GroupLayout Time_checkLayout = new javax.swing.GroupLayout(Time_check);
        Time_check.setLayout(Time_checkLayout);
        Time_checkLayout.setHorizontalGroup(
            Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Time_checkLayout.createSequentialGroup()
                .addGroup(Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Time_checkLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JlableTime, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Time_checkLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Time_checkLayout.createSequentialGroup()
                                .addGroup(Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Time_checkLayout.createSequentialGroup()
                                        .addComponent(JTextFieldDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonDistenceKiloMeter)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(Time_checkLayout.createSequentialGroup()
                                        .addGroup(Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(Time_checkLayout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(jRadioButtonMinute)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jRadioButtonHours))
                                            .addGroup(Time_checkLayout.createSequentialGroup()
                                                .addComponent(jRadioButtonSpeedKiloMeter)
                                                .addGap(0, 0, Short.MAX_VALUE))))))
                            .addGroup(Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jButtonSpeed, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDistance, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                                .addComponent(jButtontime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Time_checkLayout.setVerticalGroup(
            Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Time_checkLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlableTime, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSpeed)
                    .addComponent(jLabelDistance))
                .addGap(18, 18, 18)
                .addGroup(Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonMinute)
                    .addComponent(jRadioButtonHours))
                .addGap(18, 18, 18)
                .addGroup(Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonSpeedKiloMeter))
                .addGap(18, 18, 18)
                .addGroup(Time_checkLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTextFieldDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRadioButtonDistenceKiloMeter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtontime, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        jLabel4.setBackground(new java.awt.Color(255, 153, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 0, 153));
        jLabel4.setText("    WELCOME");

        javax.swing.GroupLayout jPanelwelcomeLayout = new javax.swing.GroupLayout(jPanelwelcome);
        jPanelwelcome.setLayout(jPanelwelcomeLayout);
        jPanelwelcomeLayout.setHorizontalGroup(
            jPanelwelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelwelcomeLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanelwelcomeLayout.setVerticalGroup(
            jPanelwelcomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelwelcomeLayout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(161, Short.MAX_VALUE))
        );

        jComboBoxSetoption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "select", "a2 – b2 = (a – b)(a + b)", "a2 + b2", "(a+b)2", "(a-b)2" }));
        jComboBoxSetoption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxSetoptionActionPerformed(evt);
            }
        });

        jTextFieldAvalue.setText("a");
        jTextFieldAvalue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldAvalueMouseClicked(evt);
            }
        });

        jTextFieldAPowerValue.setText("p");

        jTextFieldBvalue.setText("b");

        jTextFieldBpowervalue.setText("p");

        jLabel5.setText("P = power");

        jButtonOperation.setText("Ok");

        jLabelequal.setText("=");

        jTextFieldResultValue.setText("result");
        jTextFieldResultValue.setEnabled(false);

        jComboBoxOpration.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));

        jLabel13.setText("a = first value ");

        jLabel14.setText("b = second value");

        javax.swing.GroupLayout jPanelAlzabricLayout = new javax.swing.GroupLayout(jPanelAlzabric);
        jPanelAlzabric.setLayout(jPanelAlzabricLayout);
        jPanelAlzabricLayout.setHorizontalGroup(
            jPanelAlzabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlzabricLayout.createSequentialGroup()
                .addGroup(jPanelAlzabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAlzabricLayout.createSequentialGroup()
                        .addGroup(jPanelAlzabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelAlzabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelAlzabricLayout.createSequentialGroup()
                                    .addGap(46, 46, 46)
                                    .addComponent(jTextFieldAPowerValue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(76, 76, 76)
                                    .addComponent(jTextFieldBpowervalue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanelAlzabricLayout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addComponent(jComboBoxSetoption, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAlzabricLayout.createSequentialGroup()
                                    .addContainerGap()
                                    .addGroup(jPanelAlzabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanelAlzabricLayout.createSequentialGroup()
                                            .addComponent(jTextFieldAvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(14, 14, 14)
                                            .addComponent(jComboBoxOpration, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(jTextFieldBvalue, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButtonOperation, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabelequal, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTextFieldResultValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelAlzabricLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelAlzabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 27, Short.MAX_VALUE))
                    .addGroup(jPanelAlzabricLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelAlzabricLayout.setVerticalGroup(
            jPanelAlzabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAlzabricLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBoxSetoption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addGroup(jPanelAlzabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAPowerValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBpowervalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelAlzabricLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBvalue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelequal)
                    .addComponent(jTextFieldResultValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxOpration, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jButtonOperation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(50, 50, 50))
        );

        jLabel8.setText("Velocity   =");

        jLabel9.setText("final position(Xf)      --");

        jLabel10.setText("initial position (Xi)");

        jLabel11.setText("               Time (s)");

        jTextFieldvelocity.setText("velocity");
        jTextFieldvelocity.setEnabled(false);

        jTextFieldtimevelocity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtimevelocityActionPerformed(evt);
            }
        });

        jButton1.setText("Velocity");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setText(" =");

        jLabel12.setText("--");

        javax.swing.GroupLayout jPanelVelocityLayout = new javax.swing.GroupLayout(jPanelVelocity);
        jPanelVelocity.setLayout(jPanelVelocityLayout);
        jPanelVelocityLayout.setHorizontalGroup(
            jPanelVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVelocityLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVelocityLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVelocityLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(71, 71, 71))
                    .addGroup(jPanelVelocityLayout.createSequentialGroup()
                        .addGroup(jPanelVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelVelocityLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jTextFinalPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldInitialPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelVelocityLayout.createSequentialGroup()
                                .addComponent(jTextFieldvelocity, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanelVelocityLayout.createSequentialGroup()
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextFieldtimevelocity, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelVelocityLayout.setVerticalGroup(
            jPanelVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVelocityLayout.createSequentialGroup()
                .addGroup(jPanelVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVelocityLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabel8))
                    .addGroup(jPanelVelocityLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanelVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(37, 37, 37)
                .addGroup(jPanelVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFinalPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldInitialPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldvelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelVelocityLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldtimevelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(49, 49, 49)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jMenu3.setText("welcome");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu1.setText("Speed");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Alzabric Eq.");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu4.setText("velocity");
        jMenu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu4MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Time_check, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelwelcome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelAlzabric, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(20, 20, 20)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPanelVelocity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Time_check, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelwelcome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanelAlzabric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(55, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jPanelVelocity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(45, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtontimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtontimeActionPerformed
        float speed_meter = 0;
        float distance_meter = 0;
//       Speed convert kilometer to meter
        if (jRadioButtonSpeedKiloMeter.isSelected()) {
            String speed_value = jTextFieldSpeed.getText();
            float speed_km = Float.valueOf(speed_value);
            speed_meter = speed_km * 1000;
        } else {
            String speed_value = jTextFieldSpeed.getText();
            speed_meter = Float.valueOf(speed_value);
        }

//       Distance convert kilomter to meter
        if (jRadioButtonDistenceKiloMeter.isSelected()) {
            String distance_value = JTextFieldDistance.getText();
            float distance_km = Float.valueOf(distance_value);
            distance_meter = distance_km * 1000;
        } else {
            String distance_value = JTextFieldDistance.getText();
            distance_meter = Float.valueOf(distance_value);
        }

        float time = distance_meter / speed_meter;

        if (jRadioButtonHours.isSelected()) {
            time = time / 3600;
            jTextFieldTime.setText(String.valueOf(time + "House"));
        } else if (jRadioButtonMinute.isSelected()) {
            time = (time / 3600) * 60;
            jTextFieldTime.setText(String.valueOf(time + "Minutes"));
        } else {
            jTextFieldTime.setText(String.valueOf(time + "second"));
        }


    }//GEN-LAST:event_jButtontimeActionPerformed

    private void JlableTimeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JlableTimeMouseClicked
        // TODO add your handling code here:
        jButtontime.setVisible(true);
        jButtonSpeed.setVisible(false);
        jButtonDistance.setVisible(false);
        jTextFieldTime.setEditable(false);
        JTextFieldDistance.setEditable(true);
        jTextFieldSpeed.setEditable(true);
        jTextFieldTime.setText("");
        jTextFieldSpeed.setText("");
        JTextFieldDistance.setText("");


    }//GEN-LAST:event_JlableTimeMouseClicked

    private void jLabelSpeedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelSpeedMouseClicked
        // TODO add your handling code here:
        jButtonSpeed.setVisible(true);
        jButtontime.setVisible(false);
        jButtonDistance.setVisible(false);
        jTextFieldSpeed.setEditable(false);
        jTextFieldTime.setEditable(true);
        JTextFieldDistance.setEditable(true);
        jTextFieldTime.setText("");
        jTextFieldSpeed.setText("");
        JTextFieldDistance.setText("");
    }//GEN-LAST:event_jLabelSpeedMouseClicked

    private void jButtonSpeedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpeedActionPerformed
        // TODO add your handling code here:
        float time_second = 0;
        String time_value = jTextFieldTime.getText();
        float time = Float.valueOf(time_value);
        if (jRadioButtonHours.isSelected()) {
            time_second = (time * 60) * 60;
        } else if (jRadioButtonMinute.isSelected()) {
            time_second = time * 60;
        } else {
            time_second = time;
        }

//       Distance convert kilomter to meter
        float distance_meter = 0;
        String distance_value = JTextFieldDistance.getText();
        float distance = Float.valueOf(distance_value);
        if (jRadioButtonDistenceKiloMeter.isSelected()) {
            distance_meter = distance * 1000;
        } else {
            distance_meter = distance;
        }

        float speed = distance / time;

        float speed_KM = 0;

        if (jRadioButtonSpeedKiloMeter.isSelected()) {
            speed_KM = speed / 1000;
            jTextFieldSpeed.setText(String.valueOf(speed_KM + "KM"));
        } else {
            jTextFieldSpeed.setText(String.valueOf(speed_KM + "Meter"));
        }
    }//GEN-LAST:event_jButtonSpeedActionPerformed

    private void jLabelDistanceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelDistanceMouseClicked
        // TODO add your handling code here:
        jButtonSpeed.setVisible(false);
        jButtontime.setVisible(false);
        jButtonDistance.setVisible(true);
        jTextFieldSpeed.setEditable(true);
        jTextFieldTime.setEditable(true);
        JTextFieldDistance.setEditable(false);
        jTextFieldTime.setText("");
        jTextFieldSpeed.setText("");
        JTextFieldDistance.setText("");

    }//GEN-LAST:event_jLabelDistanceMouseClicked

    private void jButtonDistanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDistanceActionPerformed
        // TODO add your handling code here:

        float time_second = 0;
        String time_value = jTextFieldTime.getText();
        float time = Float.valueOf(time_value);
        if (jRadioButtonHours.isSelected()) {
            time_second = (time * 60) * 60;
        } else if (jRadioButtonMinute.isSelected()) {
            time_second = time * 60;
        } else {
            time_second = time;
        }

        float speed_meter = 0;
        String speed_value = jTextFieldSpeed.getText();
        float speed_km = Float.valueOf(speed_value);
        if (jRadioButtonSpeedKiloMeter.isSelected()) {
            speed_meter = speed_km * 1000;
        } else {
            speed_meter = speed_km;
        }

        float distance = speed_km * time;
        float distance_km = 0;
        if (jRadioButtonDistenceKiloMeter.isSelected()) {
            distance_km = distance / 1000;
            JTextFieldDistance.setText(String.valueOf(distance_km + "KM"));
        } else {
            JTextFieldDistance.setText(String.valueOf(distance_km + "Meter"));
        }
    }//GEN-LAST:event_jButtonDistanceActionPerformed

    private void jRadioButtonSpeedKiloMeterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSpeedKiloMeterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSpeedKiloMeterActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        Time_check.setVisible(false);
        jPanelwelcome.setVisible(false);
        jPanelAlzabric.setVisible(true);
        jPanelVelocity.setVisible(false);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        jPanelwelcome.setVisible(false);
        Time_check.setVisible(true);
        jPanelAlzabric.setVisible(false);
        jPanelVelocity.setVisible(false);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        // TODO add your handling code here:
        jPanelwelcome.setVisible(true);
        Time_check.setVisible(false);
        jPanelAlzabric.setVisible(false);
        jPanelVelocity.setVisible(false);


    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu4MouseClicked
        // TODO add your handling code here:
        jPanelwelcome.setVisible(false);
        Time_check.setVisible(false);
        jPanelAlzabric.setVisible(false);
        jPanelVelocity.setVisible(true);

    }//GEN-LAST:event_jMenu4MouseClicked

    private void jTextFieldtimevelocityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtimevelocityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtimevelocityActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        float time = Float.valueOf(jTextFieldtimevelocity.getText());
        float finalp = Float.valueOf(jTextFinalPosition.getText());
        float initial = Float.valueOf(jTextFieldInitialPosition.getText());
        float velocity = (finalp - initial) / time;
        jTextFieldvelocity.setText(String.valueOf(velocity));

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxSetoptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxSetoptionActionPerformed
        // TODO add your handling code here:
        switch (jComboBoxSetoption.getSelectedIndex()) {
            case 0:
                jTextFieldAPowerValue.setVisible(false);
                jTextFieldBpowervalue.setVisible(false);
                jTextFieldAvalue.setVisible(false);
                jTextFieldBvalue.setVisible(false);
                jTextFieldResultValue.setVisible(false);
                jComboBoxOpration.setVisible(false);
                jLabelequal.setVisible(false);
                jButtonOperation.setVisible(false);
                break;
            case 1:
                jTextFieldAPowerValue.setVisible(true);
                jTextFieldBpowervalue.setVisible(true);
                jTextFieldAvalue.setVisible(true);
                jTextFieldBvalue.setVisible(true);
                jTextFieldResultValue.setVisible(true);
                jComboBoxOpration.setVisible(true);
                jLabelequal.setVisible(true);
                jButtonOperation.setVisible(true);
               
                break;
            case 2:
                jTextFieldAPowerValue.setVisible(true);
                jTextFieldBpowervalue.setVisible(true);
                jTextFieldAvalue.setVisible(true);
                jTextFieldBvalue.setVisible(true);
                jTextFieldResultValue.setVisible(true);
                jComboBoxOpration.setVisible(true);
                jLabelequal.setVisible(true);
                jButtonOperation.setVisible(true);
                System.out.println("a2 – b2 = (a – b)(a + b)==2");
                break;
            case 3:
                jTextFieldAPowerValue.setVisible(true);
                jTextFieldBpowervalue.setVisible(true);
                jTextFieldAvalue.setVisible(true);
                jTextFieldBvalue.setVisible(true);
                jTextFieldResultValue.setVisible(true);
                jComboBoxOpration.setVisible(true);
                jLabelequal.setVisible(true);
                jButtonOperation.setVisible(true);
                System.out.println("a2 + b2 = (a – b)2 + 2ab==3");
                break;

            case 4:
                jTextFieldAPowerValue.setVisible(true);
                jTextFieldBpowervalue.setVisible(true);
                jTextFieldAvalue.setVisible(true);
                jTextFieldBvalue.setVisible(true);
                jTextFieldResultValue.setVisible(true);
                jComboBoxOpration.setVisible(true);
                jLabelequal.setVisible(true);
                jButtonOperation.setVisible(true);
                System.out.println("(a+b)2 = a2 + 2ab + b2==4");
                break;
            default:
                System.out.println("please select any equation==defalt");
                break;
        }
    }//GEN-LAST:event_jComboBoxSetoptionActionPerformed

    private void jTextFieldAvalueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldAvalueMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldAvalueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mathes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mathes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mathes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mathes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mathes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTextFieldDistance;
    private javax.swing.JLabel JlableTime;
    private javax.swing.JPanel Time_check;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDistance;
    private javax.swing.JButton jButtonOperation;
    private javax.swing.JButton jButtonSpeed;
    private javax.swing.JButton jButtontime;
    private javax.swing.JComboBox<String> jComboBoxOpration;
    private javax.swing.JComboBox<String> jComboBoxSetoption;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelDistance;
    private javax.swing.JLabel jLabelSpeed;
    private javax.swing.JLabel jLabelequal;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanelAlzabric;
    private javax.swing.JPanel jPanelVelocity;
    private javax.swing.JPanel jPanelwelcome;
    private javax.swing.JRadioButton jRadioButtonDistenceKiloMeter;
    private javax.swing.JRadioButton jRadioButtonHours;
    private javax.swing.JRadioButton jRadioButtonMinute;
    private javax.swing.JRadioButton jRadioButtonSpeedKiloMeter;
    private javax.swing.JTextField jTextFieldAPowerValue;
    private javax.swing.JTextField jTextFieldAvalue;
    private javax.swing.JTextField jTextFieldBpowervalue;
    private javax.swing.JTextField jTextFieldBvalue;
    private javax.swing.JTextField jTextFieldInitialPosition;
    private javax.swing.JTextField jTextFieldResultValue;
    private javax.swing.JTextField jTextFieldSpeed;
    private javax.swing.JTextField jTextFieldTime;
    private javax.swing.JTextField jTextFieldtimevelocity;
    private javax.swing.JTextField jTextFieldvelocity;
    private javax.swing.JTextField jTextFinalPosition;
    // End of variables declaration//GEN-END:variables
}
